# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncomm.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x19\n\x04Info\x12\x11\n\tsend_info\x18\x01 \x02(\t\"\x18\n\x06Header\x12\x0e\n\x06header\x18\x01 \x02(\t\"%\n\x0fMapperTextChunk\x12\x12\n\ntext_chunk\x18\x01 \x02(\t\"\xb0\x01\n\x0cReducerInput\x12\"\n\x03kvs\x18\x01 \x03(\x0b\x32\x15.ReducerInput.KVPairs\x1a|\n\x07KVPairs\x12\x12\n\nreducer_id\x18\x01 \x02(\x05\x12\x33\n\nkey_values\x18\x02 \x03(\x0b\x32\x1f.ReducerInput.KVPairs.ListItems\x1a(\n\tListItems\x12\x0c\n\x04word\x18\x01 \x02(\t\x12\r\n\x05\x63ount\x18\x02 \x02(\x05')



_INFO = DESCRIPTOR.message_types_by_name['Info']
_HEADER = DESCRIPTOR.message_types_by_name['Header']
_MAPPERTEXTCHUNK = DESCRIPTOR.message_types_by_name['MapperTextChunk']
_REDUCERINPUT = DESCRIPTOR.message_types_by_name['ReducerInput']
_REDUCERINPUT_KVPAIRS = _REDUCERINPUT.nested_types_by_name['KVPairs']
_REDUCERINPUT_KVPAIRS_LISTITEMS = _REDUCERINPUT_KVPAIRS.nested_types_by_name['ListItems']
Info = _reflection.GeneratedProtocolMessageType('Info', (_message.Message,), {
  'DESCRIPTOR' : _INFO,
  '__module__' : 'comm_pb2'
  # @@protoc_insertion_point(class_scope:Info)
  })
_sym_db.RegisterMessage(Info)

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), {
  'DESCRIPTOR' : _HEADER,
  '__module__' : 'comm_pb2'
  # @@protoc_insertion_point(class_scope:Header)
  })
_sym_db.RegisterMessage(Header)

MapperTextChunk = _reflection.GeneratedProtocolMessageType('MapperTextChunk', (_message.Message,), {
  'DESCRIPTOR' : _MAPPERTEXTCHUNK,
  '__module__' : 'comm_pb2'
  # @@protoc_insertion_point(class_scope:MapperTextChunk)
  })
_sym_db.RegisterMessage(MapperTextChunk)

ReducerInput = _reflection.GeneratedProtocolMessageType('ReducerInput', (_message.Message,), {

  'KVPairs' : _reflection.GeneratedProtocolMessageType('KVPairs', (_message.Message,), {

    'ListItems' : _reflection.GeneratedProtocolMessageType('ListItems', (_message.Message,), {
      'DESCRIPTOR' : _REDUCERINPUT_KVPAIRS_LISTITEMS,
      '__module__' : 'comm_pb2'
      # @@protoc_insertion_point(class_scope:ReducerInput.KVPairs.ListItems)
      })
    ,
    'DESCRIPTOR' : _REDUCERINPUT_KVPAIRS,
    '__module__' : 'comm_pb2'
    # @@protoc_insertion_point(class_scope:ReducerInput.KVPairs)
    })
  ,
  'DESCRIPTOR' : _REDUCERINPUT,
  '__module__' : 'comm_pb2'
  # @@protoc_insertion_point(class_scope:ReducerInput)
  })
_sym_db.RegisterMessage(ReducerInput)
_sym_db.RegisterMessage(ReducerInput.KVPairs)
_sym_db.RegisterMessage(ReducerInput.KVPairs.ListItems)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INFO._serialized_start=44
  _INFO._serialized_end=69
  _HEADER._serialized_start=71
  _HEADER._serialized_end=95
  _MAPPERTEXTCHUNK._serialized_start=97
  _MAPPERTEXTCHUNK._serialized_end=134
  _REDUCERINPUT._serialized_start=137
  _REDUCERINPUT._serialized_end=313
  _REDUCERINPUT_KVPAIRS._serialized_start=189
  _REDUCERINPUT_KVPAIRS._serialized_end=313
  _REDUCERINPUT_KVPAIRS_LISTITEMS._serialized_start=273
  _REDUCERINPUT_KVPAIRS_LISTITEMS._serialized_end=313
# @@protoc_insertion_point(module_scope)
